### PR TITLE
Fixes #34909 - register helper to `Foreman::ComputeResourcesVmsController`

### LINKED ISSUE #289: Unable to import hosts from compute resource
Hi everyone,

we upgraded our Foreman installation from 2.5.4 over 3.0.2 and 3.1.2 to 3.2.1. Since that, we are not able to import new hosts from vmware (no matter if managed or unmanaged). If we try to do it, we get the following error message:

Oops, we’re sorry but something went wrong undefined method `host_puppet_environment_field’ for #<#Class:0x000055c0b2314f20:0x00007f18f4364ae8>

I already created a ticket in Redmine with the full stack trace
https://projects.theforeman.org/issues/34909

and replied to a accordingly topic in the forum
https://community.theforeman.org/t/undefined-method-host-puppet-environment-field/25503/5

The version of foreman_puppet is 3.0.7.
Any help would be highly appreciated.

Thanks in advance and kind regards
Max

### PR DESCRIPTION
**Pull request by Ron-Lavi**
the `compute_resources_vms/import.html.erb` in Foreman is counting on the
presence of the `host_puppet_environment_field` helper from
`ForemanPuppet::HostsAndHostgroupsHelper`

@ShimShtein @stejskalleos thanks for the guidance with this issue :)

Fixes #289

### CODE REVIEW

**Review by Manisha15 — APPROVED** [review]
LGTM.

**Comment by ShimShtein** [comment]
Test failure seems unrelated, but IMHO needs fixing.
Didn't test it, but code-wise ACK from me

File: lib/foreman_puppet/engine.rb [hunk 1]
```diff
@@ -60,6 +60,7 @@ class Engine < ::Rails::Engine
       ::Api::V2::HostgroupsController.include ForemanPuppet::Extensions::ParametersHostgroup
       ::OperatingsystemsController.prepend ForemanPuppet::Extensions::OperatingsystemsController
       ::HostsController.include ForemanPuppet::Extensions::HostsControllerExtensions
+      ::ComputeResourcesVmsController.include ForemanPuppet::Extensions::ComputeResourcesVmsController
```
Comment (ezr-ondrej) [inline lib/foreman_puppet/engine.rb:63]: Wouldn't simple
```suggestion
      ::ComputeResourcesVmsController.helper ForemanPuppet::HostsAndHostgroupsHelper
```
work here as well? Then we would do without an extension for the controller.

**Review by ezr-ondrej — COMMENTED** [review]
Awesome! thanks for finding the culprint @Ron-Lavi !
One nit to simplify a code, but it is not strictly necessary ^_^

**Comment by ezr-ondrej** [comment]
Test failures are unrelated :)

File: lib/foreman_puppet/engine.rb (hunk 1 above)
Comment (Ron-Lavi) [reply lib/foreman_puppet/engine.rb]: Thanks @ezr-ondrej it works, and code looks better 👍🏼

**Review by ezr-ondrej — APPROVED** [review]
Thanks @Ron-Lavi :+1:

**Comment by ezr-ondrej** [comment]
CP 3.0: #294
